### ISSUE TITLE
Feature: batch exclude

### ISSUE THREAD

**Issue by sky5454** [YoRolling/exclude-it#13]
In embedded development, it is just necessary to exclude directories in batches.

**Comment by YoRolling** [comment]
大兄弟说的是不是 `glob` 模式， 比如 `foo/**` 会直接忽略 `foo/`下面的所有内容，不限深度的忽略。

**Comment by sky5454** [comment]
> 
> 
> 大兄弟说的是不是 `glob` 模式， 比如 `foo/**` 会直接忽略 `foo/`下面的所有内容，不限深度的忽略。

其实是希望新功能：把批量选中的目录添加到 exclude 列表里，这样便于嵌入式开发。

**Comment by YoRolling** [comment]
OK，我研究一下。，如果可以会发布新版本上去。不过可能要等等，最近福报了。

**Comment by YoRolling** [comment]
已经发布了，大兄弟可以更新看看，有什么问题可以再讨论。
