### ISSUE TITLE
Not working on drive letter different than C:

### ISSUE THREAD

**Issue by lllopo** [YoRolling/exclude-it#3]
My projects are located on drive D: and when I try to exclude a file it says some thing of the sorts, that the file "C:\d:\xxx\xxx.txt" was not found. Obviously the drive letter C: is hardcoded or prepended wrongly somehow.

**Comment by lllopo** [comment]
Exact message :
ENOENT: no such file or directory, access 'C:\d:\Projects\*****\****.txt'

I'm trying to exclude it from the workspace.

**Comment by YoRolling** [comment]
Sorry for your problem， I will work for it  tomorrow ，I will comment here  when I get any steps  。 

Thanks again for your support。

很抱歉你在使用过程中出现了问题，明天我会尝试追踪跟进这个问题，一旦有了新进展，我会在这里告诉你。
再次感谢你的支持！

**Comment by YoRolling** [comment]
#4 ,fixed bugs. It should works on Windows.  If you still get any error , tell me please.
