### ISSUE TITLE
Context Menu names

### ISSUE THREAD

**Issue by richard-scott** [YoRolling/exclude-it#7]
Hi, Great extension. Would it be better to rename "Exclude: global", to be "Exclude: user" and change "Exclude: workspace" to "Exclude: folder".

The reason being, that in a [Multi-root Workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) you can add Multiple project folders as sub folders. When you right click to hide something and choose "Exclude: workspace" it only hides files in that folder, and not the workspace, you need to click "Exclude: global" to hide the files in the whole workspace.

**Comment by YoRolling** [comment]
Thanks for your attention！ It should be a good idea, coming with next release。
Best wishes for you !
